language: python
sudo: false
python:
  - "3.6"
  - "3.5"
  - "nightly"
install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
  - pip install -e .
  - pip install check-manifest flake8
