dist: xenial
language: python
sudo: false
cache:
  - pip
install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements-dev.txt
  - pip install --upgrade -r requirements.txt
  - pip freeze
  - pip install .
script:
  - $TEST_CMD
after_success:
  - codecov
matrix:
  include:
    - name: "mypy"
      python: 3.6
      env:
        - TEST_CMD="mypy bookstore --ignore-missing-imports"
    - name: "black"
      python: 3.6
      env:
        - TEST_CMD="black --check --verbose ."
    - name: "flake8"
      python: 3.6
      env:
        - TEST_CMD="flake8 bookstore"
    - name: "py36"
      python: 3.6
      env:
        - TEST_CMD="pytest -v --maxfail=2 bookstore/tests"
    - name: "py37"
      python: 3.7
      env:
        - TEST_CMD="pytest -v --maxfail=2 bookstore/tests"

