language: python
sudo: false
python:
  - 3.6
  - nightly
install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements-dev.txt
  - pip install -e .
  - pip install check-manifest flake8
